
// Login
POST  http://localhost:5000/api/auth/login
Content-Type:  application/json

{
    //"email":"thientaurus2804@gmail.com",
    //"googleId":"n1A2y6KL6lN41cqaEhaa0mdXOFX2"
     "email":"thientaurus2804@gmail.com",
     "googleId":"n1A2y6KL6lN41cqaEhaa0mdXOFX2"
}


###
POST  http://localhost:5000/api/auth/register
Content-Type:  application/json

{
  "googleId": "1234",
  "avatarUrl": "avatar.jpg",
  "email": "vy@gmail.com",
  "nickName": "John",
  "displayLanguage":"en",
  "nativeLanguage": "vn"
  
}



// Login
###
POST  http://localhost:5000/api/auth/adminLogin
Content-Type:  application/json

{
    "username":"admin",
    "password":"123"
}


###
POST  http://localhost:5000/api/auth/adminRegister
Content-Type:  application/json

{
  "username":"admin",
  "password": "123"
}