PUT https://wd4dz44x-5000.asse.devtunnels.ms/api/listen/createOrUpdatePlaylist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTUxYzE1ZDg3YTQxMDdkY2ViYTZjNjciLCJlbWFpbCI6ImhvcXVhbmdsaW5oMjcxMEBnbWFpbC5jb20iLCJpYXQiOjE2OTk5MzM5MTMsImV4cCI6MTcwMjUyNTkxM30.3tTebxRxWBrCMXH3M7fOX5QxNbwf7csAirZpwWfIgdA
Content-Type: application/json

{
  "favoriteUserIds": ["65421becd899b95c139a1df1","6551c15d87a4107dceba6c67"],
  "favoriteLectureIds":["6540bd721860dada50828c4d"]
}

###
GET https://wd4dz44x-5000.asse.devtunnels.ms/api/listen/getLecturesAvailable
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTUxYzE1ZDg3YTQxMDdkY2ViYTZjNjciLCJlbWFpbCI6ImhvcXVhbmdsaW5oMjcxMEBnbWFpbC5jb20iLCJpYXQiOjE2OTk5MzM5MTMsImV4cCI6MTcwMjUyNTkxM30.3tTebxRxWBrCMXH3M7fOX5QxNbwf7csAirZpwWfIgdA

###
GET  https://wd4dz44x-5000.asse.devtunnels.ms/api/listen/getUsersAvailable
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU2ZWQxZDU1NjFjOWY4YjFlMmY4YmYiLCJlbWFpbCI6ImhvcXVhbmdsaW5oMjcxMEBnbWFpbC5jb20iLCJpYXQiOjE3MDA1NDc0ODcsImV4cCI6MTcwMzEzOTQ4N30.zoCVeMScBjaohDsgkz9Y-iXWiJXxAz9gbfU-bUjZRSM




###
GET  https://wd4dz44x-5000.asse.devtunnels.ms/api/listen/getPlaylistListenByLecture?lectureId=6540bd721860dada50828c4d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU2ZWQxZDU1NjFjOWY4YjFlMmY4YmYiLCJlbWFpbCI6ImhvcXVhbmdsaW5oMjcxMEBnbWFpbC5jb20iLCJpYXQiOjE3MDA1NDc0ODcsImV4cCI6MTcwMzEzOTQ4N30.zoCVeMScBjaohDsgkz9Y-iXWiJXxAz9gbfU-bUjZRSM



###
GET  https://wd4dz44x-5000.asse.devtunnels.ms/api/listen/getPlaylistSummary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU2ZWQxZDU1NjFjOWY4YjFlMmY4YmYiLCJlbWFpbCI6ImhvcXVhbmdsaW5oMjcxMEBnbWFpbC5jb20iLCJpYXQiOjE3MDA1NDc0ODcsImV4cCI6MTcwMzEzOTQ4N30.zoCVeMScBjaohDsgkz9Y-iXWiJXxAz9gbfU-bUjZRSM