####
GET http://localhost:5000/api/user/lectures?stage=0&sort=-1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTQyMWQzNGQ4OTliOTVjMTM5YTFkZjQiLCJlbWFpbCI6Imhhb0BnbWFpbC5jb20iLCJpYXQiOjE2OTg5ODEzMjUsImV4cCI6MTcwMTU3MzMyNX0.ww-nRZNTj1l797QeCEEld4i3YPCeNcypNr4ZymuWebE

//Add
####
PUT https://r5200nc8-5000.asse.devtunnels.ms/api/user/addOrUpdateEnrollment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTRiYjgzODE0NjNmYmJhY2ExMzRjYjgiLCJlbWFpbCI6InZ5QGdtYWlsLmNvbSIsImlhdCI6MTY5OTUxMTkzOSwiZXhwIjoxNzAyMTAzOTM5fQ.XIHmbJMHczAA_Wk3hVpVIkcBZ_DXFMm2hF00k9fZf4k
Content-Type: application/json

{
   "lectureId": "6540bd721860dada50828c4d"
}


//Update
####
PUT https://r5200nc8-5000.asse.devtunnels.ms/api/user/addOrUpdateEnrollment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTRiYjgzODE0NjNmYmJhY2ExMzRjYjgiLCJlbWFpbCI6InZ5QGdtYWlsLmNvbSIsImlhdCI6MTY5OTUxMTkzOSwiZXhwIjoxNzAyMTAzOTM5fQ.XIHmbJMHczAA_Wk3hVpVIkcBZ_DXFMm2hF00k9fZf4k
Content-Type: application/json

{
   "enrollmentId":"654c86551860dada50ac77ad",
   "lectureId": "6540bd721860dada50828c4d"
}