GET http://localhost:5000/api/vocabulary/getVocabularyById/6541daf81860dada50d18c3e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTRiYjgzODE0NjNmYmJhY2ExMzRjYjgiLCJlbWFpbCI6InZ5QGdtYWlsLmNvbSIsImlhdCI6MTY5OTUxMTkzOSwiZXhwIjoxNzAyMTAzOTM5fQ.XIHmbJMHczAA_Wk3hVpVIkcBZ_DXFMm2hF00k9fZf4k 
