GET http://localhost:5000/api/vocabulary/getVocabularyById/6541daf81860dada50d18c3e
?lectureId=6540bd721860dada50828c4d&stage=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTQyMWJlY2Q4OTliOTVjMTM5YTFkZjEiLCJlbWFpbCI6InRoaWVudGF1cnVzMjgwNEBnbWFpbC5jb20iLCJpYXQiOjE2OTk0MTExNTIsImV4cCI6MTcwMjAwMzE1Mn0.jjg2Lhvyea7g6Z6Mglsd5dUE9Ffl5xPDB20JHJUyA_E